### ISSUE TITLE
Syloti in Syloti Nagri script

### ISSUE THREAD

**Issue by brawer** [unicode-org/udhr#12]
In https://github.com/googlei18n/noto-fonts/issues/998, @Sagir8453 gave a translation of the Universal Declaration of Human Rights to the Syloti langauge in the Syloti Nagri script (BCP47 language code: `syl-Sylo`). Unfortunately, they’ve only translated one single sentence:

ꠢꠇꠟ ꠝꠣꠘꠥ ꠀꠎꠣꠖ ꠅꠁꠀ ꠢꠝꠣꠘ ꠁꠎ꠆ꠎꠔ ꠀꠞ ꠢꠇ ꠟꠁꠀ ꠙꠄꠖꠣ ꠅꠄ। ꠔꠣꠞꠣꠞ ꠛꠤꠛꠦꠇ ꠀꠞ ꠀꠇꠟ ꠀꠍꠦ। ꠄꠞ ꠟꠣꠉꠤ ꠢꠇꠟꠦ ꠄꠇꠎꠘꠦ ꠀꠞꠇꠎꠘꠞ ꠟꠉꠦ ꠛꠤꠞꠣꠖꠞꠤꠞ ꠝꠘꠥꠜꠣꠛ ꠟꠁꠀ ꠀꠌꠞꠘ ꠇꠞꠔꠦ ꠟꠣꠉꠦ।

@Sagir8453, would you mind translating the entire text (including preamble and the 30 articles)? Similar to what Unicode.org already has for [Bangla](http://www.unicode.org/udhr/d/udhr_ben.html), [English](http://www.unicode.org/udhr/d/udhr_eng.html), or [Assamese](http://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/asm.pdf). Then, the translation for Syloti (Nagri) would be in the same state as the other [existing translations](http://www.unicode.org/udhr/translations.html). By the way, a translation to Syloti written in Bangla letters would also be useful; currently, we don’t have anything in Syloti yet.

**Comment by eric-muller** [comment]
With no action since 2017, it seems unlikely this would progress. Closing.
