### ISSUE TITLE
Corrections to Kannada 

### ISSUE THREAD

**Issue by srinidhi97** [unicode-org/udhr#16]
Two years ago I had requested to correct Kannada text, which was subsequently updated.
However, I still find many spelling mistakes in UDHR text of Kannada. In some cases extra spaces in between or within the words are included. These have been corrected. The highlighted portion in Yellow shows the corrected words/phrases in the attached document.
The text was verified from the document http://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/kjv.pdf
[udhr_kannada.docx](https://github.com/unicode-org/udhr/files/1510593/udhr_kannada.docx)

Srinidhi A

**Comment by eric-muller** [comment]
Fixed. Thanks!
