### ISSUE TITLE
Language code for Topkegola/Tokpegola is likely ola for Walungge

### ISSUE THREAD

**Issue by brawer** [unicode-org/udhr#19]
Proposal: Change `019_deva` to `ola_deva`, and change `019_tibt` to `ola_tibt`. According to [Ethnologue](https://www.ethnologue.com/language/ola) and [another site](http://www.peoplegroups.org/Explore/groupdetails.aspx?peid=48450), Topkegola is the name of a people whose language is Walungge (BCP47: `ola`). It seems that both Topkegola and Tokpegola are in use as English name.

**Comment by eric-muller** [comment]
019_deva and 019_tibt are only filenames and are (now) pretty much arbitrary. I would prefer to leave them unchanged for stability.

On the other hand, they are currently  iso639-3='und'. If there is evidence that the language is Walungge (ola), then we can change their iso639-3 and bcp47 attributes.

**Comment by eric-muller** [comment]
No evidence has surfaced so far. Closing.
