### ISSUE TITLE
Errors in German translation

### ISSUE THREAD

**Issue by ivan-pan** [unicode-org/udhr#20]
I sent an email to Eric Muller in 2017 but got no reply, so I want to present some of my remarks here, **adding new ones**:

There are two spelling mistakes in the German translation of the UDHR according to the reformed orthography (deu_1996): “zuteil werden” should be “zuteilwerden” (written as one word since 2006) and “des weiteren” should be “des Weiteren” (written with a capital W already since 1996). Regarding the translation in traditional orthography (deu_1901), two missing commas were added. You may consider removing the one in “gleichgültig, ob” because according to the (old) Duden rule R 126, if the construction is seen as a unit, no comma is usually placed before the actual conjunction, and according to R 127, the use of the comma is optional in some constructions (“je nachdem[,] ob” is given as an example).

The same goes for deu_1996: “Added two missing commas and removed and [sic!] extra comma, thanks to Otto Stolz.” § 74 E1 of the reformed orthography states that if the introduction of a dependent clause consists of an introductory word and further words, (1) one places a comma before the whole word group (2) and in some cases the writer can [!] place an additional comma between the parts of the word group. The sentence “Ich komme morgen, gleichviel(,) ob er es will oder nicht.” is among the examples, the comma is not obligatory. The comma that was apparently removed (the one in “Niemand darf gezwungen werden, einer Vereinigung anzugehören”) is not forbidden either (§ 75).

Both the deu_1901 and the deu_1996 translation miss a comma between “Leistungen” and “gewährleistet”: “der seine und seiner Familie Gesundheit und Wohl, einschließlich Nahrung, Kleidung, Wohnung, ärztlicher Versorgung und notwendiger sozialer Leistungen gewährleistet, sowie […]” In fact, the HTML version at ohchr.org has two “gewährleistet”, and while the second one was retained in the Unicode translations, the PDF version at ohchr.org has the first one, so you may consider changing to this: “der seine und seiner Familie Gesundheit und Wohl gewährleistet, einschließlich Nahrung, Kleidung, Wohnung, ärztlicher Versorgung und notwendiger sozialer Leistungen, sowie […]” (The PDF version still has “ärztliche Versorgung und notwendige soziale Leistungen” instead of “ärztlicher Versorgung und notwendiger sozialer Leistungen” in the genitive.)

Finally, for the _Notes on German (1996)_, I would recommend using these up-to-date URLs instead of the ones currently present there:

2017 documents

Rules (edited in 2018): http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2016_redigiert_2018.pdf
Word list: http://www.rechtschreibrat.com/DOX/rfdr_Woerterverzeichnis_2016_veroeffentlicht_2017.pdf

2011 documents

Rules: http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2011.pdf
Word list: http://www.rechtschreibrat.com/DOX/rfdr_Woerterverzeichnis_2011.pdf

2006 documents

Rules: http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2006.pdf
Word list: http://www.rechtschreibrat.com/DOX/rfdr_Woerterverzeichnis_2006.pdf

2004 documents

Rules and word list: http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2004.pdf

1996 documents

Rules and word list (not on official site): http://nts.uni-due.de/links/regel.pdf
HTML version (Wayback Machine): https://web.archive.org/web/20050601062959/http://www.ids-mannheim.de/reform/

(The HTML version at udoklinger.de is of low quality.)

**Comment by brawer** [comment]
If you don’t mind, can you send a pull request via GitHub to make these changes?

**Comment by ivan-pan** [comment]
Yes, sorry, am new to GitHub.

**Comment by brawer** [comment]
Thank you! Merged.
