### ISSUE TITLE
Aromanian or Vlax Romany ?

### ISSUE THREAD

**Issue by r12a** [unicode-org/udhr#23]
The UDHR source names this language as Aromanian [rup], but uses a BCP47 code of [rmy], which is Vlax Romani. Which is it?

https://unicode.org/udhr/d/udhr_rmy.html

**Comment by eric-muller** [comment]
The OHCHR site sometime incorrectly identifies languages. The "news" section records this particular case:

  <para><emphasis>June 21, 2015:</emphasis> the language of the [rmy] translation was incorrectly identified as “Romani, Vlax”. It is in fact “Aromanian”, ISO 639-3 rup, BCP 47 rup. Thanks to Kevin Scannell for reporting this error.</para>
