### ISSUE TITLE
Incomplete Northern Sami Article 1 translation

### ISSUE THREAD

**Issue by AlsoScratch** [unicode-org/udhr#25]
The translation of Article 1 of UDHR in Northern Sami (`sme`) is missing the second sentence.

While I couldn't bother to check if the other parts had anything missing, Omniglot has kindly [provided us a translation of Article 1 in Northern Sami:](https://omniglot.com/udhr/uralic.htm#sami)

> Buot olbmot leat riegádan friddjan ja olmmošárvvu ja olmmošvuoigatvuođaid dáfus. Sii leat jierbmalaš olbmot geain lea oamedovdu ja sii gálggaše leat dego vieljačagat.

**Comment by r12a** [comment]
What was the resolution for this comment? At https://unicode.org/udhr/d/udhr_sme.html i see:

> Buot olbmot leat riegádan friddjan ja olmmošárvvu ja olmmošvuoigatvuođaid dáfus dássásaččat,

**Comment by r12a** [comment]
Ah, i just came across the emails related to https://github.com/unicode-org/udhr/pull/26#event-2670276636

Would be good to link the issue and the PR as standard practice.

**Comment by AlsoScratch** [comment]
Hope they update it soon.
