### ISSUE TITLE
Transliterations of Sanskrit UDHR using Aksharamukha

### ISSUE THREAD

**Issue by twardoch** [unicode-org/udhr#36]
I’ve used the [Python version](https://pypi.org/project/aksharamukha/) of the [Aksharamukha](https://aksharamukha.appspot.com/) script converter to transliterate the Sanskrit UDHR into some 47 scripts that currently have no translation. 

The results are in [my fork](https://github.com/twardoch/udhr/tree/master/data/udhr-translit) and the code is [there, too](https://github.com/twardoch/udhr/tree/master/translit) — unfortunately it right now uses an unpublished module. 

However — I wonder, is this something of value for the official repo?

**Comment by eric-muller** [comment]
Following an off line discussion, we agreed to not include transliterations in this project.
