### ISSUE TITLE
License of data files?

### ISSUE THREAD

**Issue by davidmalcolm** [unicode-org/udhr#39]
I see that the data files typically have:
  `© The Office of the High Commisioner for Human Rights`
or
  `© 1996 – 2009 The Office of the High Commissioner for Human Rights`
but there doesn't seem to be any license grant allowing people to use these files.

Are the data files under some kind of Open Source or Creative Commons license or somesuch? (perhaps https://www.unicode.org/license.html ?)

I was hoping to write a script to transform the data files to a different format and potentially redistribute the result, and wondered what the license terms would be - but as it stands the data appears to be effectively proprietary, which I assume is not the intent.

**Comment by eric-muller** [comment]
There is no license. 

It is very unlikely that the OHCHR would object to the distribution of the text of the UDHR.
