### ISSUE TITLE
Fix Khmer spelling, spacing, and input sequences

### ISSUE THREAD

**Issue by sovichet** [unicode-org/udhr#42]
There are several spacing errors, wrong spellings and input sequences in the Khmer doc.
I've highlighted them in the attached PDF. (Orange: Spacing Error; Yellow: Spelling/Sequence Error)

I've uploaded the fixes here: https://github.com/sovichet/udhr/commit/939e72e8882089ba29f86a6d7c09604007f628e6

Attachment:
[UDHR_Khmer_Issues.pdf](https://github.com/unicode-org/udhr/files/8699352/UDHR_Khmer_Issues.pdf)

**Comment by eric-muller** [comment]
Thanks a lot for your fixes, they are now incorporated.
