### ISSUE TITLE
Corrections to Sanskrit , Marathi, Hindi

### ISSUE THREAD

**Issue by sridatta1** [unicode-org/udhr#8]
I came to know about this repository, I was about to send a mail.
 Following Corrections are requested for UDHR Translations.
1. Replacement of colon by Visarga

The Sanskrit Translation uses colon instead of Devanagari Visarga everywhere.
In word पूर्णत: of article 10(अनुच्छेद १०.) of Hindi translation, colon is used in lieu of Visarga.
In Marathi Translation, colon is used instead of Visarga in the words स्वच्छंदत:, वस्तुत: and स्वत:
It is requested to replace colon by Visarga(0903) in all these cases.

2. Corrections to Sanskrit translation
 Due to visual similarity the text uses य्व(yva) in place of ख(kha) everywhere.
The text uses ढ़ in place of  ढ in the words दृढ़ीकृतवन्तः and दृढ़ीकृता in प्रस्तावना(Preamble).

 The text uses  स्वातन्ञ्य in place of  स्वातन्त्र्य due to visual similarity
 At the beginning of  Article 12, द्वादशोऽनुच्छेद:( translation-12th article) is used.Since this is repetitive it must be removed.

It is requested to use Devanagari digits, similar to Hindi,Marathi,Nepali UDHR translations etc.

Translation of the word 'National' as 'राष्ट्रीय' is incorrect in Sanskrit even though is common and valid in Hindi and other Indian languages, the correct form according to Sanskrit Grammar is राष्ट्रिय,for more information see  https://goo.gl/znNrFX by Shriramana Sharma

 
Article 13 states [missing?], the second sentence स्वदेशोपेतं कमपि देशं त्यक्तुं स्वदेशं च प्रत्यागन्तुं प्रत्येकमपि अधिकृतोऽस्ति। is itself the translation of  'Everyone has the right to leave any country, including his own, and to return to his country.' Therefore no text is missing, similarly in Articles 14, 15 and 20.
In article 26, para 2  मानवीय व्यक्तित्वस्य and मौलिक स्वातन्ञ्याणां are to be replaced by मानवीय-व्यक्तित्वस्य and मौलिक-स्वातन्त्रन्त्र्याणां respectively

**Comment by behnam** [comment]
Thanks for the reports, @sridatta1. Could you please submit pull requests (PR) to fix these?

You can use the GitHub text editor for it, which is very fast and easy for small edits like this (and means you don't need to use any git commands or even a command line or IDE). You can fix all the issues in one PR, or make separate smaller edits, if needed.

For example, for Sanskrit data, open the data file (https://github.com/unicode-org/udhr/blob/master/data/udhr/udhr_san.xml), click on the Edit (pencil icon) on the top-right corner of the file, make the changes, and submit the PR for it.

**Comment by eric-muller** [comment]
On the visarga: I made the replacements requested. Just to be sure:

- there is one U+003A COLON left in the Marathi translation, in article 25: "हक्क आहे: सर्व मुलांना"

- in the Sanskrit translation, I changed all colons, including the article titles ("अनुच्छेदः") and "स्वत्वाधिकारः 1997" at the end.

> Due to visual similarity the text uses य्व(yva) in place of ख(kha) everywhere.

Done.

> The text uses ढ़ in place of ढ in the words दृढ़ीकृतवन्तः and दृढ़ीकृता in प्रस्तावना(Preamble).

Not done. All 3 nuktas are clearly present in the original. The "policy" is to respect the source as much as possible, i.e. to fix only things that are clearly wrong, and leaves things that are possible alone. If need be, we can add another translation. Of course, the boundary is not a bright line. So I would just want to make sure that the nuktas are errors before removing them.

> The text uses स्वातन्ञ्य in place of स्वातन्त्र्य due to visual similarity

Done.

> At the beginning of Article 12, द्वादशोऽनुच्छेद:( translation-12th article) is used.Since this is repetitive it must be removed.

Done.

> It is requested to use Devanagari digits, similar to Hindi,Marathi,Nepali UDHR translations etc.

Done. I used the digits without "." for the article numbers, and the digits between () for the list items. Not sure that () are appropriate for Sanskrit, please let me know if this needs to be changed.

> Translation of the word 'National' as 'राष्ट्रीय' is incorrect in Sanskrit even though is common and valid in Hindi and other Indian languages, the correct form according to Sanskrit Grammar is राष्ट्रिय,

Done for all 7 occurrences.

> Article 13 states [missing?],  ... similarly in Articles 14, 15 and 20.

Done.

> In article 26, para 2 मानवीय व्यक्तित्वस्य and मौलिक स्वातन्ञ्याणां are to be replaced by मानवीय-व्यक्तित्वस्य and मौलिक-स्वातन्त्रन्त्र्याणां respectively

Not done. Same question as for the nuktas.

If it is not imposing too much: currently, the preamble is just one big paragraph. However, it is normally made of 8 pieces (as in <http://ccnmtl.columbia.edu/projects/mmt/udhr/>). Can you tell us how to break it in those pieces?

Many thanks,

**Comment by eric-muller** [comment]
Most changes done, no action on the rest for two years. Closing, feel free to reopen with specific changes.
